### ISSUE TITLE
`OSGiServiceProvider` uses NOOP implementation of the `MDCAdapter`

### ISSUE THREAD

**Issue by amitjoy** [osgi/slf4j-osgi#117]
I am wondering if the `OSGiServiceProvider` should use the basic `MDC` implementation - `BasicMDCAdapter` instead of `NOPMDCAdapter` which is currently used - https://github.com/osgi/slf4j-osgi/blob/af1a6f153000ec4bca660a83a01530c329d398b3/src/main/java/org/osgi/slf4j/OSGiServiceProvider.java#L55

Due to the usage of the `NOPMDCAdapter`, nothing seems to be logged at all.

**Comment by bjhargrave** [comment]
The OSGi Log Service is not MDC-aware (like slf4j-simple) unlike Logback, for example. So there is no point in using BasicMDCAdaptor.

**Comment by amitjoy** [comment]
Thanks BJ for the quick answer. Yeah, you are right. OSGi Logger is not MDC aware at all. I am sot sure why the logs ain't getting captured somehow. I will further debug my current setup if I have done something wrong or missed something.
